### ISSUE TITLE
Port to self-hosted ClojureScript

### ISSUE THREAD

**Issue by arichiardi** [binaryage/env-config#1]
Hi Darwin!

In an attempt to achieve this https://github.com/binaryage/cljs-oops/issues/8, I am looking at porting the files. Everything is smooth except for `logging.clj`. The dynamic resolution is really something that it is though to achieve in self-host, and requires calls to `cljs.js` as you might know.

I am afraid the change might be substantial there, still ok with the port?

**Comment by darwin** [comment]
I think that self-hosted version should not do any dynamic resolution. It should simply defer to `console.log` or similar node.js logging mechanism.

**Comment by darwin** [comment]
As a second thought I wonder why you even port env-config. cljs-oops can work just fine without env-config support. You simply provide an empty map to cljs-oops as part of configuration which would normally come from env-config. 

But of course having complete port with reading environment config from node.js env variables would be better. Depends on your use-case.

**Comment by arichiardi** [comment]
The problem is that oops does require `env-config`, and that triggers the problem.
Probably in oops I can just wrap in `:clj` readers the parts that call env-config, you are right it would be great to have them but I don't strictly need them.

**Comment by arichiardi** [comment]
Ok so I came across [makrovich](https://github.com/cgrand/macrovich), which seems like a good tool for solving the problem of a full port. Leaving it here for reference.

**Comment by darwin** [comment]
In my opinion env-config is a very low-level library. Ideally it should not bring any external dependencies into the project which uses it. If there is some functionality in makrovich which would be needed, it would be better to vendor it into env-config or write it from scratch.

**Comment by dupuchba** [comment]
Running into similar issue with env-config on lumo.
Unfortunatly I don't have the time to look for a solution.

Thanks for this awesome library that works perfectly under classical `cljs`
